version: '3.8'

services:
  booksmainapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/main_app

  mongo-db:
    image: mongo
    restart: always
    env_file:
      .env
    ports:
      - 27017:27017
