version: '3.8'

services:
  booksmainapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - postgres-db
    ports:
      - 8000:8000
    volumes:
      - .:/main_app

  postgres-db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
