version: '3.8'

services:
  booksmainapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/main_app

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nero
      MONGO_INITDB_ROOT_PASSWORD : nero
      MONGO_INITDB_DATABASE: nero
    ports:
      - 27017:27017
