# Generated by Django 3.2.6 on 2021-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_squashed_0003_alter_author_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
