# Generated by Django 3.2.6 on 2021-09-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
            preserve_default=False,
        ),
    ]
