# Generated by Django 3.2.6 on 2021-09-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('google_book_api', '0001_initial'), ('google_book_api', '0002_book_isbn'), ('google_book_api', '0003_auto_20210905_1924'), ('google_book_api', '0004_auto_20210905_1925'), ('google_book_api', '0005_auto_20210905_1927'), ('google_book_api', '0006_auto_20210905_1929'), ('google_book_api', '0007_book_slug'), ('google_book_api', '0008_auto_20210907_2059'), ('google_book_api', '0009_auto_20210913_2041')]

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kind', models.CharField(blank=True, max_length=100)),
                ('api_book_id', models.CharField(max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publish_data', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('authors', models.ManyToManyField(to='authors.Author')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
