# Generated by Django 3.0.5 on 2021-04-28 22:19

from django.db import migrations, models
import djongo.models.fields
import google_book_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBookApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField()),
                ('api_book_id', models.TextField()),
                ('title', models.TextField()),
                ('authors', djongo.models.fields.ArrayField(model_container=google_book_api.models.Author)),
                ('publisher', models.TextField()),
                ('publish_data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
