# Generated by Django 3.0.5 on 2021-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_book_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlebookapi',
            name='api_book_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='googlebookapi',
            name='kind',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='googlebookapi',
            name='publish_data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='googlebookapi',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='googlebookapi',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
