# Generated by Django 3.2.6 on 2021-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_book_api', '0005_auto_20210905_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='google_book_api.Author'),
        ),
    ]
