# Generated by Django 3.2.6 on 2021-09-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_book_api', '0006_auto_20210905_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
