# Generated by Django 3.2.6 on 2021-09-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_book_api', '0007_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='api_book_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
